version: '3.3'
services: 
  lunch:
    image: 'lalyos/lunch:v4'
    #build: .
    ports:
    - '80'
    environment:
    - TITLE=${TITLE:-Development}
    - COLOR=${COLOR:-lightgreen}
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - food:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
  util:
    image: cmd.cat/curl
    command: sleep 9999
volumes:
  food: 