version: '3.3'
services: 
  lunch:
    image: 'lunch:v4'
    #build: .
    ports:
    - '80'
    environment:
    - TITLE=coffebreak-soon
    - COLOR=lightblue
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - food:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  food: 