version: '3.3'
services: 
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  coffe:
    image: lalyos/12factor:boujee
    ports:
      - "80"
    environment:
      - TITLE=coffebreak
      - VIRTUAL_HOST=coffee.vcap.me
      - VIRTUAL_PORT=80
  lunch:
    image: 'lalyos/lunch:v4'
    #build: .
    ports:
    - '80'
    environment:
    - VIRTUAL_HOST=lunch.vcap.me
    - VIRTUAL_PORT=80
    - TITLE=${TITLE:-Development}
    - COLOR=${COLOR:-lightgreen}
    - BODY=${BODY:-Please use TITLE/COLOR/BODY}
  mydb:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=s3cr3t
    volumes:
    - food:/var/lib/postgresql/data
    - ./sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    environment:
    - VIRTUAL_HOST=adminer.vcap.me
    - VIRTUAL_PORT=8080
    ports:
      - 8080
  util:
    image: cmd.cat/curl
    command: sleep 9999
volumes:
  food: 